### ISSUE TITLE
windows 缺少ssl DLL 

### ISSUE THREAD

**Issue by sbdx** [lsk569937453/Spire#49]
> 由于找不到 libssl-3-x64.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
> 由于找不到 libcrypto-3-x64.dll，无法继续执行代码。重新安装程序可能会解决此问题。 

Win11 专业版 21H2 22000.2295

这种DLL不是所有环境都默认安装的，建议打包到压缩包或静态编译。

**Comment by lsk569937453** [comment]
#50 已经修复了这个问题，可以从release 页面下载0.0.10
